[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
bindeps = true

[build]
target = "x86_64-unknown-none"
#target = "x86_64-boatshine_os.json"

#[target.'cfg(target_os="none")']
#runner = "bootimage runner"